name: "Release build"

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+*"

permissions:
  contents: write

jobs:
  optimize:
    name: "Optimize Smart Contract"
    runs-on: ubuntu-latest
    steps:
      - name: Set tag as version
        run: echo "VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV  # set env.VERSION=v0.0.0

      - name: Checkout source
        uses: actions/checkout@v2
        
      - name: Optimize smart contract
        run: ./scripts/optimizer.sh

      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v0.1.15
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
            tag_name: ${{ env.VERSION }}
            body: ${{ github.event.pull_request.body }}
            files: |
                ./artifacts/*.wasm
                ./artifacts/checksums.txt
            draft: false
            prerelease: false
